"$schema" = 'https://starship.rs/config-schema.json'

palette = 'catppuccin_mocha'

format = """
[](red)\
$os\
$username\
[](bg:peach fg:red)\
$directory\
[](bg:yellow fg:peach)\
$git_branch\
$git_commit\
$git_metrics\
$git_state\
$git_status\
[](fg:yellow bg:green)\
$dart\
$golang\
$java\
$kotlin\
$lua\
$nodejs\
$python\
$rust\
[](fg:green bg:sapphire)\
$conda\
$docker_context\
[](fg:sapphire bg:lavender)\
$time\
[ ](fg:lavender)\
$cmd_duration\
$line_break\
$shell\
$sudo\
$character"""

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[cmd_duration]
show_milliseconds = false
format = "  en $duration "
style = "bg:lavender"
disabled = false
show_notifications = true
min_time = 1000
min_time_to_notify = 30000

[directory]
truncation_length = 5
truncate_to_repo = false
format = "[ $path]($style)[$read_only ]($read_only_style)"
style = "bg:peach fg:crust"
disabled = false
read_only = " 󰌾"
read_only_style = "bg:peach fg:crust"
truncation_symbol = "…/"
before_repo_root_style = "bg:peach fg:crust"
repo_root_style = "bg:peach fg:blue"
repo_root_format = "[  $before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only ]($read_only_style)"
home_symbol = "󱂵 "
use_os_path_sep = true
fish_style_pwd_dir_length = 0
use_logical_path = true

[directory.substitutions]
"Documents" = "󰲂 "
"Downloads" = "󰉍 "
"Music" = "󱍙 "
"Pictures" = "󰉏 "
"Videos" = ""
"Documentos" = "󰈙 "
"Descargas" = "󰉍 "
"Música" = "󱍙 "
"Imágenes" = "󰉏 "
"dev" = "󰲋 "
"Vídeos" = ""

[line_break]
disabled = false

[os]
disabled = false
style = "bg:red fg:crust"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Manjaro = ""
NixOS = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"

[shell]
bash_indicator = ""
cmd_indicator = ""
disabled = false
fish_indicator = '󰈺'
format = "[$indicator]($style) "
powershell_indicator = "󰨊"
style = "fg:text"
unknown_indicator = ""
zsh_indicator = '\$_'

[sudo]
allow_windows = false
disabled = false
format = "[$symbol]($style) "
style = "fg:overlay0"
symbol = "󱅨"

[time]
disabled = false
time_format = "%I:%M %p"
style = "bg:lavender"
format = '[[   $time ](fg:crust bg:lavender)]($style)'

[username]
show_always = true
style_user = "bg:red fg:crust"
style_root = "bg:red fg:crust"
format = '[ $user]($style)'

[docker_context]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $context) ](fg:crust bg:sapphire)]($style)'

[git_branch]
always_show_remote = false
disabled = false
ignore_branches = []
only_attached = false
truncation_length = 9223372036854775807
truncation_symbol = "…"
symbol = ""
style = "bg:yellow"
format = '[[ $symbol $branch(:$remote_branch) ](fg:crust bg:yellow)]($style)'

[git_commit]
commit_hash_length = 7
disabled = false
format = "[($hash$tag) ]($style)"
only_detached = true
style = "bg:yellow"
tag_disabled = true
tag_max_candidates = 0
tag_symbol = " 🏷 "

[git_metrics]
added_style = "bg:yellow"
deleted_style = "bg:yellow"
disabled = true
format = "([+$added ]($added_style))([-$deleted ]($deleted_style))"
ignore_submodules = false
only_nonzero_diffs = true

[git_state]
am = "AM"
am_or_rebase = "AM/REBASE"
bisect = "BISECTING"
cherry_pick = "CHERRY-PICKING"
disabled = false
format = "([$state( $progress_current/$progress_total) ]($style))"
merge = "MERGING"
rebase = "REBASING"
revert = "REVERTING"
style = "bg: yellow"

[git_status]
ahead = "[⇡$count ](bg:yellow fg:blue)"
behind = "[⇣$count ](bg:yellow fg:blue)"
conflicted = "[=$count ](bg:yellow fg:maroon)"
deleted = "[✘$count ](bg:yellow fg:mauve)"
disabled = false
diverged = "[⇕$count ](bg:yellow fg:maroon)"
ignore_submodules = false
modified = "[!$count ](bg:yellow fg:peach)"
renamed = "[»$count ](bg:yellow fg:mauve)"
staged = '[+$count ](bg:yellow fg:green)'
format = '[[($all_status$ahead_behind)](fg:crust bg:yellow)]($style)'
stashed = "[$$count ](bg:yellow fg:peach)"
style = "bg:yellow"
typechanged = "$count ](bg:yellow fg:lavender)"
untracked = "[?$count ](bg:yellow fg:pink)"
# up_to_date = "[󰚰$count ](bg:yellow)"
use_git_executable = false

[conda]
symbol = "  "
style = "fg:crust bg:sapphire"
format = '[$symbol$environment ]($style)'
ignore_base = false

[dart]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[golang]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[java]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[kotlin]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[lua]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[nodejs]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[python]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version)(\( $virtualenv\)) ](fg:crust bg:green)]($style)'

[rust]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

