"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio          = [ 1, 4, 3 ]
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse 	 = false
sort_dir_first = true
sort_translit  = false
linemode       = "size_and_mtime"
show_hidden    = false
show_symlink   = true
scrolloff      = 5
mouse_events   = [ "click", "scroll" ]
title_format   = "Yazi: {cwd}"

[preview]
wrap            = "no"
tab_size        = 2
max_width       = 600
max_height      = 900
cache_dir       = "~/.cache/yazi/"
image_delay     = 30
image_filter    = "triangle"
image_quality   = 75
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]

[opener]
Abrir = [
	{ run = 'xdg-open "$1"', orphan = true, desc = "Abrir", for = "linux" },
]
Editar = [
	{ run = 'nvim "$@"', desc = "Editar con neovim", block = true,                for = "linux" },
	{ run = 'nano "$@"', desc = "Editar con nano",   block = true,                for = "linux" },
	{ run = 'code "$@"', desc = "VScode", block = true, orphan = true, for = "linux" },
]
Explorador = [
	{ run = 'xdg-open "$(dirname "$1")"', desc = "Explorador", for = "linux" },
]
Extraer = [
	{ run = 'ya pub extract --list "$@"', desc = "Extraer aquí", for = "linux" },
]
Imagen = [
  { run = 'loupe "$@"',    orphan = true, desc = "Visor de imágenes",    for = "linux" },
  { run = 'gimp "$@"',     orphan = true, desc = "GIMP",     for = "linux" },
  { run = 'inkscape "$@"', orphan = true, desc = "Inkscape", for = "linux" },
]
LibreOffice = [
	{ run = 'libreoffice "$@"', orphan = true, desc = "LibreOffice", for = "linux" },
]
Pdf = [
	{ run = 'evince "$@"', orphan = true, desc = "Visor de Pdf", for = "linux" },
]
Reproducir = [
	{ run = 'totem "$@"', orphan = true, desc = "Reproductor", for = "linux" },
]

[open]
rules = [
	# Folder
	{ name = "*/", use = [ "Explorador", "Editar", "Abrir" ] },
	# Text
	{ mime = "text/*", use = [ "Editar", "Explorador" ] },
	# Image
	{ mime = "image/*", use = [ "Imagen", "Explorador" ] },
	# Media
	{ mime = "{audio,video}/*", use = [ "Reproducir", "Explorador" ] },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "Extraer", "Explorador" ] },
	# JSON
	{ mime = "application/{json,ndjson}", use = [ "Editar", "Explorador" ] },
	{ mime = "*/javascript", use = [ "Editar", "Explorador" ] },
	# PDF
	{ mime = "application/pdf", use = [ "Pdf", "Explorador" ] },
	# Empty file
	{ mime = "inode/empty", use = [ "Editar", "Explorador" ] },
	# LibreOffice
  { name = "*.{odt,ott,fodt,ods,ots,fods,odp,otp,fodp,odg,otg,fodg,odf,odb}", use = [ "LibreOffice", "Explorador" ] },
  { name = "*.{doc,docx,dot,dotx,docm,dotm,rtf,xls,xlsx,xlw,xlt,xlsm,xltx,xltm,xlsb,ppt,pptx,pps,ppsx,pot,potx,pptm,potm}", use = [ "LibreOffice", "Explorador" ] },
  { name = "*.{csv,txt,wk1,wks,123,dif,dbf,slk,wb2,numbers,htm,html,xml,sxw,sxc,sxi,sxd,sdc,vor,uos,uof}", use = [ "LibreOffice", "Explorador" ] },
	# Fallback
	{ name = "*", use = [ "Abrir", "Explorador" ] },
]

[tasks]
micro_workers    = 10
macro_workers    = 10
bizarre_retry    = 3
image_alloc      = 134217728  # 128MB
image_bound      = [ 5000, 5000 ]
suppress_preload = false

[plugin]
fetchers = [
	# Mimetype
	{ id = "mime", name = "*", run = "mime", prio = "high" },
]
spotters = [
	{ name = "*/", run = "folder" },
	# Code
	{ mime = "text/*", run = "code" },
	{ mime = "application/{mbox,javascript,wine-extension-ini}", run = "code" },
	# Image
	{ mime = "image/{avif,hei?,jxl}", run = "magick" },
	{ mime = "image/svg+xml", run = "svg" },
	{ mime = "image/*", run = "image" },
	# Video
	{ mime = "video/*", run = "video" },
	# Fallback
	{ name = "*", run = "file" },
]
preloaders = [
	# Image
	{ mime = "image/{avif,hei?,jxl}", run = "magick" },
	{ mime = "image/svg+xml", run = "svg" },
	{ mime = "image/*", run = "image" },
	# Video
	{ mime = "video/*", run = "video" },
	# PDF
	{ mime = "application/pdf", run = "pdf" },
	# Font
	{ mime = "font/*", run = "font" },
	{ mime = "application/ms-opentype", run = "font" },
]
previewers = [
	{ name = "*/", run = "folder" },
	# Code
	{ mime = "text/*", run = "code" },
	{ mime = "application/{mbox,javascript,wine-extension-ini}", run = "code" },
	# JSON
	{ mime = "application/{json,ndjson}", run = "json" },
	# Image
	{ mime = "image/{avif,hei?,jxl}", run = "magick" },
	{ mime = "image/svg+xml", run = "svg" },
	{ mime = "image/*", run = "image" },
	# Video
	{ mime = "video/*", run = "video" },
	# PDF
	{ mime = "application/pdf", run = "pdf" },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", run = "archive" },
	{ mime = "application/{debian*-package,redhat-package-manager,rpm,android.package-archive}", run = "archive" },
	{ name = "*.{AppImage,appimage}", run = "archive" },
	# Virtual Disk / Disk Image
	{ mime = "application/{iso9660-image,qemu-disk,ms-wim,apple-diskimage}", run = "archive" },
	{ mime = "application/virtualbox-{vhd,vhdx}", run = "archive" },
	{ name = "*.{img,fat,ext,ext2,ext3,ext4,squashfs,ntfs,hfs,hfsx}", run = "archive" },
	# Font
	{ mime = "font/*", run = "font" },
	{ mime = "application/ms-opentype", run = "font" },
	# Empty file
	{ mime = "inode/empty", run = "empty" },
	# Fallback
	{ name = "*", run = "file" },
]
prepend_preloaders = [
    # Office Documents
    { mime = "application/openxmlformats-officedocument.*", run = "office" },
    { mime = "application/oasis.opendocument.*", run = "office" },
    { mime = "application/ms-*", run = "office" },
    { mime = "application/msword", run = "office" },
    { name = "*.docx", run = "office" },
]
prepend_previewers = [
    # Office Documents
    { mime = "application/openxmlformats-officedocument.*", run = "office" },
    { mime = "application/oasis.opendocument.*", run = "office" },
    { mime = "application/ms-*", run = "office" },
    { mime = "application/msword", run = "office" },
    { name = "*.docx", run = "office" },
]

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"

[input]
cursor_blink = false

# cd
cd_title  = "Cambiar directorio:"
cd_origin = "top-center"
cd_offset = [ 0, 2, 50, 3 ]

# create
create_title  = [ "Crear:", "Crear (directorio):" ]
create_origin = "top-center"
create_offset = [ 0, 2, 50, 3 ]

# rename
rename_title  = "Renombrar:"
rename_origin = "hovered"
rename_offset = [ 0, 1, 50, 3 ]

# filter
filter_title  = "Filtrar:"
filter_origin = "top-center"
filter_offset = [ 0, 2, 50, 3 ]

# find
find_title  = [ "Buscar hacia siguiente:", "Buscar hacia atrás:" ]
find_origin = "top-center"
find_offset = [ 0, 2, 50, 3 ]

# search
search_title  = "Buscar via {n}:"
search_origin = "top-center"
search_offset = [ 0, 2, 50, 3 ]

# shell
shell_title  = [ "Shell:", "Shell (block):" ]
shell_origin = "top-center"
shell_offset = [ 0, 2, 50, 3 ]

[confirm]
# trash
trash_title 	= "¿Mover a la papelera {n} archivo{s} seleccionado{s}?"
trash_origin	= "center"
trash_offset	= [ 0, 0, 70, 20 ]

# delete
delete_title 	= "¿Borrar permanentemente {n} archivo{s} seleccionado{s}?"
delete_origin	= "center"
delete_offset	= [ 0, 0, 70, 20 ]

# overwrite
overwrite_title   = "¿Sobrescribir el archivo?"
overwrite_content = "Se Sobrescribirá el siguiente archivo:"
overwrite_origin  = "center"
overwrite_offset  = [ 0, 0, 50, 15 ]

# quit
quit_title   = "¿Salir?"
quit_content = "Aún hay tareas en ejecución. ¿Estás seguro de que deseas salir?"
quit_origin  = "center"
quit_offset  = [ 0, 0, 50, 15 ]

[pick]
open_title  = "Abrir con:"
open_origin = "hovered"
open_offset = [ 0, 1, 50, 7 ]

[which]
sort_by      	 = "none"
sort_sensitive = false
sort_reverse 	 = false
sort_translit  = false
